In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
# load dataset
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# drop unnecessary columns
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

X = df.drop('Survived', axis=1)
y = df['Survived']

In [4]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [5]:
# numerical columns
num_cols = ['Age', 'SibSp', 'Parch', 'Fare']

# categorical columns
cat_cols = ['Pclass', 'Sex', 'Embarked']

In [6]:
# numerical pipeline
num_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# categorical pipeline
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [7]:
# preprocessing
preprocessor = ColumnTransformer([
    ('num', num_pipe, num_cols),
    ('cat', cat_pipe, cat_cols)
])

In [8]:
# Random Forest model
model = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    min_samples_leaf=2,
    random_state=42
)

In [9]:
# complete pipeline
pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', model)
])

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred))

Accuracy: 0.8100558659217877

In [10]:
X_test

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
565       3    male  24.0      2      0  24.1500        S
160       3    male  44.0      0      1  16.1000        S
553       3    male  22.0      0      0   7.2250        C
860       3    male  41.0      2      0  14.1083        S
241       3  female   NaN      1      0  15.5000        Q
..      ...     ...   ...    ...    ...      ...      ...
880       2  female  25.0      0      1  26.0000        S
91        3    male  20.0      0      0   7.8542        S
883       2    male  28.0      0      0  10.5000        S
473       2  female  23.0      0      0  13.7917        C
637       2    male  31.0      1      1  26.2500        S

[179 rows x 7 columns]

In [17]:
dict= {
    'Pclass': 3,
    'Sex': 'male',
    'Age': 34,
    'SibSp': 0,
    'Parch': 0,
    'Fare':56.4958,
    'Embarked':'S'
}

In [18]:
test_input = pd.DataFrame([dict])

In [19]:
pipe.predict(test_input)

array([1])

In [ ]:
import pickle

with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model saved successfully!")